#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Matlab on June 01, 2026 at 14:57:14.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[309];
extern c_float ldata[588];
extern c_float udata[588];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[309];
extern c_float Dinvscaling[309];
extern c_float Escaling[588];
extern c_float Einvscaling[588];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[897];
extern c_int linsys_solver_P[897];
extern c_float linsys_solver_bp[897];
extern c_float linsys_solver_sol[897];
extern c_float linsys_solver_rho_inv_vec[588];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[309];
extern c_float ysolution[588];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[588];
extern c_float work_rho_inv_vec[588];
extern c_float work_x[309];
extern c_float work_y[588];
extern c_float work_z[588];
extern c_float work_xz_tilde[897];
extern c_float work_x_prev[309];
extern c_float work_z_prev[588];
extern c_float work_Ax[588];
extern c_float work_Px[309];
extern c_float work_Aty[309];
extern c_float work_delta_y[588];
extern c_float work_Atdelta_y[309];
extern c_float work_delta_x[309];
extern c_float work_Pdelta_x[309];
extern c_float work_Adelta_x[588];
extern c_float work_D_temp[309];
extern c_float work_D_temp_A[309];
extern c_float work_E_temp[588];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
